// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNlsLGa_z9Zx7Q8vKoIp4dx2D4U9Vn1ew',
    appId: '1:1057203832826:web:794ae383e87cf7bb6d0643',
    messagingSenderId: '1057203832826',
    projectId: 'hotel-booking-app-6ac71',
    authDomain: 'hotel-booking-app-6ac71.firebaseapp.com',
    storageBucket: 'hotel-booking-app-6ac71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9wwK4S_JAowOw4C-ZVbynHTA77T_YtgU',
    appId: '1:1057203832826:android:a2e7305bf7abee926d0643',
    messagingSenderId: '1057203832826',
    projectId: 'hotel-booking-app-6ac71',
    storageBucket: 'hotel-booking-app-6ac71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1sztbg4pHDLubeLqg3Pmuz8mltPpYqD8',
    appId: '1:1057203832826:ios:ee11cb2f1e4372ba6d0643',
    messagingSenderId: '1057203832826',
    projectId: 'hotel-booking-app-6ac71',
    storageBucket: 'hotel-booking-app-6ac71.appspot.com',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1sztbg4pHDLubeLqg3Pmuz8mltPpYqD8',
    appId: '1:1057203832826:ios:ee11cb2f1e4372ba6d0643',
    messagingSenderId: '1057203832826',
    projectId: 'hotel-booking-app-6ac71',
    storageBucket: 'hotel-booking-app-6ac71.appspot.com',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNlsLGa_z9Zx7Q8vKoIp4dx2D4U9Vn1ew',
    appId: '1:1057203832826:web:678506a1872164106d0643',
    messagingSenderId: '1057203832826',
    projectId: 'hotel-booking-app-6ac71',
    authDomain: 'hotel-booking-app-6ac71.firebaseapp.com',
    storageBucket: 'hotel-booking-app-6ac71.appspot.com',
  );
}
